### ISSUE TITLE
issues with rendering landing page statically on heroku

### ISSUE THREAD

**Issue by akelch11** [TigerAppsOrg/SpaceTiger#4]
having issues with making the landing page image render on heroku, but is rendering on production build locally.

Look through commit history to see attemtpts, but I've tried:

-setting <img src={require('./landing.jpg')}

-importing image url at top of Landing.jsx:
import landing as './landing.jpg'
...
img src={landing}

creating static folder in src folder, rendering image from there

import landing as '../../static/landing.jpg'
...
img src={landing}

All these render the landing image locally, but don't show up on Heroku. Maybe we look into putting the image url on the cloudenary they use to render their team pictures?

**Comment by nicholaspad** [comment]
i'm pretty sure it's because it has to be in the `frontend/public` directory, can you try that?

**Comment by nicholaspad** [comment]
also does the favicon need to be in that directory too?

**Comment by akelch11** [comment]
favicon is already in that directory and working. I tried importing an image from frontend/public but it says you can't import files from outside of frontend/src

<img width="787" alt="image" src="https://user-images.githubusercontent.com/62965092/220502150-21673620-862f-4131-a8d5-163a35b89648.png">

**Comment by shannon-heh** [comment]
@akelch11 maybe check out these lines? 

https://github.com/TigerAppsOrg/SpaceTiger/commit/57685faec7dccd1fdd683e23e03b0db681e91527#diff-48658425b08ff6807ec0e40ecb127dd74d3497168f1805453435d99baf78da1bR12-R26

this code is from SpaceTiger's first frontend commit, which includes some boilerplate code provided by the react bootstrapping library. i was looking into how they imported the logo images from the public directory

**you might need to specify `%PUBLIC_URL%` if you want to import images in the public folder.**

**Comment by akelch11** [comment]
resolved!

**Comment by nicholaspad** [comment]
#5
